using System.Text;
using System.Text.RegularExpressions;

class Program
{
    // Пути
    private static readonly string SourceDir = @"C:\Anything\Study\ИП\IP";
    private static readonly string TargetDir = @"C:\Anything\Study";

    // Выходные файлы
    private static readonly string CodeOutputFile = Path.Combine(TargetDir, "AllCode.txt");
    private static readonly string SystemOutputFile = Path.Combine(TargetDir, "SystemFiles.txt");

    // Расширения, которые считаются кодом (исходники приложения)
    private static readonly HashSet<string> CodeExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        ".cs",                    // C#
        ".js", ".jsx",            // JavaScript / React
        ".ts", ".tsx",            // TypeScript / React
        ".html", ".htm",          // HTML
        ".css", ".scss", ".sass", ".less", // Стили
        ".vue",                   // Vue.js
        ".svelte",                // Svelte
        ".astro"                  // Astro
    };

    // Расширения, которые считаются системными (конфиги, проектные файлы и т.п.)
    private static readonly HashSet<string> SystemExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        ".csproj", ".sln", ".json", ".config", ".xml", ".resx", ".settings",
        ".xaml", ".cshtml", ".razor", ".ruleset", ".editorconfig", ".nuspec",
        ".props", ".targets", ".yml", ".yaml", ".md", ".txt",
    };

    // Папки, которые нужно полностью игнорировать
    private static readonly HashSet<string> IgnoredFolders = new(StringComparer.OrdinalIgnoreCase)
    {
        "bin", "obj", "debug", "release", "packages", "node_modules",
        ".vs", ".git", ".idea", "TestResults", "logs", "dist", "build"
    };

    static void Main()
    {
        Directory.CreateDirectory(TargetDir);

        // Удаляем предыдущие версии файлов
        if (File.Exists(CodeOutputFile)) File.Delete(CodeOutputFile);
        if (File.Exists(SystemOutputFile)) File.Delete(SystemOutputFile);

        var allFiles = Directory.EnumerateFiles(SourceDir, "*.*", SearchOption.AllDirectories)
            .Where(file => !ShouldIgnoreFile(file));

        int codeCount = 0, systemCount = 0;

        foreach (string file in allFiles)
        {
            string extension = Path.GetExtension(file).ToLowerInvariant();
            string relativePath = Path.GetRelativePath(SourceDir, file);

            if (CodeExtensions.Contains(extension))
            {
                // Для .cs дополнительно проверяем автогенерацию
                if (extension == ".cs" && IsAutoGenerated(file))
                {
                    Console.WriteLine($"Исключён авто: {relativePath}");
                    continue;
                }

                AppendToFile(CodeOutputFile, relativePath, File.ReadAllText(file, Encoding.UTF8));
                codeCount++;
                Console.WriteLine($"Добавлен код: {relativePath}");
            }
            else if (SystemExtensions.Contains(extension))
            {
                AppendToFile(SystemOutputFile, relativePath, File.ReadAllText(file, Encoding.UTF8));
                systemCount++;
                Console.WriteLine($"Добавлен системный: {relativePath}");
            }
            // иначе пропускаем (бинарные, изображения и пр.)
        }

        Console.WriteLine($"\nГотово! Обработано файлов кода: {codeCount}, системных: {systemCount}");
        Console.WriteLine($"Код сохранён в: {CodeOutputFile}");
        Console.WriteLine($"Системные файлы сохранены в: {SystemOutputFile}");
        Console.ReadKey();
    }

    // Проверка, нужно ли игнорировать файл (по пути)
    private static bool ShouldIgnoreFile(string filePath)
    {
        string[] pathParts = filePath.Split(Path.DirectorySeparatorChar);
        return pathParts.Any(part => IgnoredFolders.Contains(part));
    }

    // Проверка на автогенерированный .cs файл
    private static bool IsAutoGenerated(string filePath)
    {
        string fileName = Path.GetFileName(filePath);
        if (Regex.IsMatch(fileName, @"AssemblyInfo|GlobalUsings|\.g\.[^\\]+$|AssemblyAttributes", RegexOptions.IgnoreCase))
            return true;

        try
        {
            string[] lines = File.ReadLines(filePath, Encoding.UTF8).Take(2).ToArray();
            return lines.Any(l => l.Contains("<auto-generated>") || l.Contains("<autogenerated"));
        }
        catch
        {
            return true;
        }
    }

    // Добавление содержимого файла в выходной файл с заголовком
    private static void AppendToFile(string outputPath, string relativePath, string content)
    {
        using (var writer = new StreamWriter(outputPath, true, Encoding.UTF8))
        {
            writer.WriteLine("// ===============================================");
            writer.WriteLine($"// Файл: {relativePath}");
            writer.WriteLine("// ===============================================");
            writer.WriteLine(content);
            writer.WriteLine();
        }
    }
}