using System.Text;
using System.Text.RegularExpressions;

class Program
{
    private static readonly string SourceDir = @"C:\Anything\Study\РПП\STO-Hook-Hands";
    private static readonly string TargetDir = @"C:\Anything\Study\РПП";
    private static readonly string OutputFile = Path.Combine(TargetDir, "Listing.txt");

    private static readonly HashSet<string> CodeExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        ".cs", ".js", ".jsx", ".ts", ".tsx",
        ".html", ".htm", ".css", ".scss", ".sass", ".less",
        ".vue", ".svelte", ".astro"
    };

    private static readonly HashSet<string> IgnoredFolders = new(StringComparer.OrdinalIgnoreCase)
    {
        "bin", "obj", "debug", "release", "packages", "node_modules",
        ".vs", ".git", ".idea", "TestResults", "logs", "dist", "build"
    };

    static void Main()
    {
        Directory.CreateDirectory(TargetDir);

        if (File.Exists(OutputFile))
            File.Delete(OutputFile);

        var allFiles = Directory.EnumerateFiles(SourceDir, "*.*", SearchOption.AllDirectories)
            .Where(file => !ShouldIgnoreFile(file));

        int count = 0;

        foreach (string file in allFiles)
        {
            string extension = Path.GetExtension(file).ToLowerInvariant();
            if (!CodeExtensions.Contains(extension))
                continue;

            // Пропускаем явно автогенерированные .cs (можно убрать при желании)
            if (extension == ".cs" && IsAutoGenerated(file))
            {
                Console.WriteLine($"Пропущен автогенерированный: {Path.GetRelativePath(SourceDir, file)}");
                continue;
            }

            string content = File.ReadAllText(file, Encoding.UTF8);

            // Запись в общий файл без заголовков и комментариев
            File.AppendAllText(OutputFile, content + Environment.NewLine, Encoding.UTF8);
            count++;
        }

        Console.WriteLine($"Готово! Файлов кода добавлено: {count}");
        Console.WriteLine($"Листинг сохранён в: {OutputFile}");
        Console.ReadKey();
    }

    private static bool ShouldIgnoreFile(string filePath)
    {
        string[] pathParts = filePath.Split(Path.DirectorySeparatorChar);
        return pathParts.Any(part => IgnoredFolders.Contains(part));
    }

    private static bool IsAutoGenerated(string filePath)
    {
        string fileName = Path.GetFileName(filePath);
        if (Regex.IsMatch(fileName, @"AssemblyInfo|GlobalUsings|\.g\.[^\\]+$|AssemblyAttributes", RegexOptions.IgnoreCase))
            return true;

        try
        {
            string[] lines = File.ReadLines(filePath, Encoding.UTF8).Take(2).ToArray();
            return lines.Any(l => l.Contains("<auto-generated>") || l.Contains("<autogenerated"));
        }
        catch
        {
            return true;
        }
    }
}